CREATE TABLE PRODUTOS (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(500),
    PRECO DOUBLE DEFAULT 0.0,
    CATEGORIA_ID INTEGER,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ATIVO CHAR(1) DEFAULT 'S'
);